### ISSUE TITLE
[Question] aosp12: ART_STACK_OVERFLOW_GAP_riscv64, why do we need larger for non-ASAN

### ISSUE THREAD

**Issue by unicornx** [riscv-android-src/platform-art#1]
https://github.com/riscv-android-src/platform-art/blob/a2017b15dbfebc2c951b3e1fec3c2dc7608741de/build/art.go#L101

why do we use 16384 for rv64, can we use the same default 8192 as other platforms?

**Comment by guoyinchen** [comment]
it is due to riscv code size is more larger than other platform

**Comment by unicornx** [comment]
Thanks, I will close this issue now
